# Generated by Django 2.0.4 on 2018-04-11 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crawl',
            new_name='ScrapyItem',
        ),
    ]
