# Generated by Django 2.0.4 on 2018-04-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0002_auto_20180411_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapyitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='scrapyitem',
            name='url',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
