# Generated by Django 2.0.4 on 2018-04-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0003_auto_20180413_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapyitem',
            name='date',
            field=models.DateField(),
        ),
    ]
